require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/match_donations", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # MatchDonation. As you add validations to MatchDonation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MatchDonation.create! valid_attributes
      get match_donations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      match_donation = MatchDonation.create! valid_attributes
      get match_donation_url(match_donation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_match_donation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      match_donation = MatchDonation.create! valid_attributes
      get edit_match_donation_url(match_donation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MatchDonation" do
        expect {
          post match_donations_url, params: { match_donation: valid_attributes }
        }.to change(MatchDonation, :count).by(1)
      end

      it "redirects to the created match_donation" do
        post match_donations_url, params: { match_donation: valid_attributes }
        expect(response).to redirect_to(match_donation_url(MatchDonation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MatchDonation" do
        expect {
          post match_donations_url, params: { match_donation: invalid_attributes }
        }.to change(MatchDonation, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post match_donations_url, params: { match_donation: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested match_donation" do
        match_donation = MatchDonation.create! valid_attributes
        patch match_donation_url(match_donation), params: { match_donation: new_attributes }
        match_donation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the match_donation" do
        match_donation = MatchDonation.create! valid_attributes
        patch match_donation_url(match_donation), params: { match_donation: new_attributes }
        match_donation.reload
        expect(response).to redirect_to(match_donation_url(match_donation))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        match_donation = MatchDonation.create! valid_attributes
        patch match_donation_url(match_donation), params: { match_donation: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested match_donation" do
      match_donation = MatchDonation.create! valid_attributes
      expect {
        delete match_donation_url(match_donation)
      }.to change(MatchDonation, :count).by(-1)
    end

    it "redirects to the match_donations list" do
      match_donation = MatchDonation.create! valid_attributes
      delete match_donation_url(match_donation)
      expect(response).to redirect_to(match_donations_url)
    end
  end
end
