require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/single_donations", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SingleDonation. As you add validations to SingleDonation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SingleDonation.create! valid_attributes
      get single_donations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      single_donation = SingleDonation.create! valid_attributes
      get single_donation_url(single_donation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_single_donation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      single_donation = SingleDonation.create! valid_attributes
      get edit_single_donation_url(single_donation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SingleDonation" do
        expect {
          post single_donations_url, params: { single_donation: valid_attributes }
        }.to change(SingleDonation, :count).by(1)
      end

      it "redirects to the created single_donation" do
        post single_donations_url, params: { single_donation: valid_attributes }
        expect(response).to redirect_to(single_donation_url(SingleDonation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SingleDonation" do
        expect {
          post single_donations_url, params: { single_donation: invalid_attributes }
        }.to change(SingleDonation, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post single_donations_url, params: { single_donation: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested single_donation" do
        single_donation = SingleDonation.create! valid_attributes
        patch single_donation_url(single_donation), params: { single_donation: new_attributes }
        single_donation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the single_donation" do
        single_donation = SingleDonation.create! valid_attributes
        patch single_donation_url(single_donation), params: { single_donation: new_attributes }
        single_donation.reload
        expect(response).to redirect_to(single_donation_url(single_donation))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        single_donation = SingleDonation.create! valid_attributes
        patch single_donation_url(single_donation), params: { single_donation: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested single_donation" do
      single_donation = SingleDonation.create! valid_attributes
      expect {
        delete single_donation_url(single_donation)
      }.to change(SingleDonation, :count).by(-1)
    end

    it "redirects to the single_donations list" do
      single_donation = SingleDonation.create! valid_attributes
      delete single_donation_url(single_donation)
      expect(response).to redirect_to(single_donations_url)
    end
  end
end
